-- noinspection SqlNoDataSourceInspectionForFile

DROP INDEX patchset_announcement_project_name_change_num_patchset_num_idx;
DROP INDEX patchset_announcement_ts_idx;
DROP TABLE patchset_announcements;
