// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/storj/changesetchihuahua/slack (interfaces: EventedChatSystem)

// Package app_test is a generated GoMock package.
package app_test

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	messages "github.com/storj/changesetchihuahua/messages"
	slack "github.com/storj/changesetchihuahua/slack"
	reflect "reflect"
)

// MockEventedChatSystem is a mock of EventedChatSystem interface
type MockEventedChatSystem struct {
	ctrl     *gomock.Controller
	recorder *MockEventedChatSystemMockRecorder
}

// MockEventedChatSystemMockRecorder is the mock recorder for MockEventedChatSystem
type MockEventedChatSystemMockRecorder struct {
	mock *MockEventedChatSystem
}

// NewMockEventedChatSystem creates a new mock instance
func NewMockEventedChatSystem(ctrl *gomock.Controller) *MockEventedChatSystem {
	mock := &MockEventedChatSystem{ctrl: ctrl}
	mock.recorder = &MockEventedChatSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventedChatSystem) EXPECT() *MockEventedChatSystemMockRecorder {
	return m.recorder
}

// GetInstallingUser mocks base method
func (m *MockEventedChatSystem) GetInstallingUser(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstallingUser", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstallingUser indicates an expected call of GetInstallingUser
func (mr *MockEventedChatSystemMockRecorder) GetInstallingUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstallingUser", reflect.TypeOf((*MockEventedChatSystem)(nil).GetInstallingUser), arg0)
}

// GetUserInfoByID mocks base method
func (m *MockEventedChatSystem) GetUserInfoByID(arg0 context.Context, arg1 string) (messages.ChatUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByID", arg0, arg1)
	ret0, _ := ret[0].(messages.ChatUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByID indicates an expected call of GetUserInfoByID
func (mr *MockEventedChatSystemMockRecorder) GetUserInfoByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByID", reflect.TypeOf((*MockEventedChatSystem)(nil).GetUserInfoByID), arg0, arg1)
}

// HandleEvent mocks base method
func (m *MockEventedChatSystem) HandleEvent(arg0 context.Context, arg1 slack.ChatEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleEvent indicates an expected call of HandleEvent
func (mr *MockEventedChatSystemMockRecorder) HandleEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockEventedChatSystem)(nil).HandleEvent), arg0, arg1)
}

// InformBuildAborted mocks base method
func (m *MockEventedChatSystem) InformBuildAborted(arg0 context.Context, arg1 messages.MessageHandle, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InformBuildAborted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InformBuildAborted indicates an expected call of InformBuildAborted
func (mr *MockEventedChatSystemMockRecorder) InformBuildAborted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InformBuildAborted", reflect.TypeOf((*MockEventedChatSystem)(nil).InformBuildAborted), arg0, arg1, arg2)
}

// InformBuildFailure mocks base method
func (m *MockEventedChatSystem) InformBuildFailure(arg0 context.Context, arg1 messages.MessageHandle, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InformBuildFailure", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InformBuildFailure indicates an expected call of InformBuildFailure
func (mr *MockEventedChatSystemMockRecorder) InformBuildFailure(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InformBuildFailure", reflect.TypeOf((*MockEventedChatSystem)(nil).InformBuildFailure), arg0, arg1, arg2)
}

// InformBuildStarted mocks base method
func (m *MockEventedChatSystem) InformBuildStarted(arg0 context.Context, arg1 messages.MessageHandle, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InformBuildStarted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InformBuildStarted indicates an expected call of InformBuildStarted
func (mr *MockEventedChatSystemMockRecorder) InformBuildStarted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InformBuildStarted", reflect.TypeOf((*MockEventedChatSystem)(nil).InformBuildStarted), arg0, arg1, arg2)
}

// InformBuildSuccess mocks base method
func (m *MockEventedChatSystem) InformBuildSuccess(arg0 context.Context, arg1 messages.MessageHandle, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InformBuildSuccess", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InformBuildSuccess indicates an expected call of InformBuildSuccess
func (mr *MockEventedChatSystemMockRecorder) InformBuildSuccess(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InformBuildSuccess", reflect.TypeOf((*MockEventedChatSystem)(nil).InformBuildSuccess), arg0, arg1, arg2)
}

// LookupChannelByName mocks base method
func (m *MockEventedChatSystem) LookupChannelByName(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupChannelByName", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupChannelByName indicates an expected call of LookupChannelByName
func (mr *MockEventedChatSystemMockRecorder) LookupChannelByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupChannelByName", reflect.TypeOf((*MockEventedChatSystem)(nil).LookupChannelByName), arg0, arg1)
}

// LookupUserByEmail mocks base method
func (m *MockEventedChatSystem) LookupUserByEmail(arg0 context.Context, arg1 string) (messages.ChatUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(messages.ChatUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupUserByEmail indicates an expected call of LookupUserByEmail
func (mr *MockEventedChatSystemMockRecorder) LookupUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupUserByEmail", reflect.TypeOf((*MockEventedChatSystem)(nil).LookupUserByEmail), arg0, arg1)
}

// SendChannelNotification mocks base method
func (m *MockEventedChatSystem) SendChannelNotification(arg0 context.Context, arg1, arg2 string) (messages.MessageHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChannelNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(messages.MessageHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendChannelNotification indicates an expected call of SendChannelNotification
func (mr *MockEventedChatSystemMockRecorder) SendChannelNotification(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChannelNotification", reflect.TypeOf((*MockEventedChatSystem)(nil).SendChannelNotification), arg0, arg1, arg2)
}

// SendChannelReport mocks base method
func (m *MockEventedChatSystem) SendChannelReport(arg0 context.Context, arg1, arg2 string, arg3 []string) (messages.MessageHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChannelReport", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(messages.MessageHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendChannelReport indicates an expected call of SendChannelReport
func (mr *MockEventedChatSystemMockRecorder) SendChannelReport(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChannelReport", reflect.TypeOf((*MockEventedChatSystem)(nil).SendChannelReport), arg0, arg1, arg2, arg3)
}

// SendNotification mocks base method
func (m *MockEventedChatSystem) SendNotification(arg0 context.Context, arg1, arg2 string) (messages.MessageHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", arg0, arg1, arg2)
	ret0, _ := ret[0].(messages.MessageHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendNotification indicates an expected call of SendNotification
func (mr *MockEventedChatSystemMockRecorder) SendNotification(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockEventedChatSystem)(nil).SendNotification), arg0, arg1, arg2)
}

// SendPersonalReport mocks base method
func (m *MockEventedChatSystem) SendPersonalReport(arg0 context.Context, arg1, arg2 string, arg3 []string) (messages.MessageHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPersonalReport", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(messages.MessageHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPersonalReport indicates an expected call of SendPersonalReport
func (mr *MockEventedChatSystemMockRecorder) SendPersonalReport(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPersonalReport", reflect.TypeOf((*MockEventedChatSystem)(nil).SendPersonalReport), arg0, arg1, arg2, arg3)
}

// SetIncomingMessageCallback mocks base method
func (m *MockEventedChatSystem) SetIncomingMessageCallback(arg0 func(string, string, bool, string) string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIncomingMessageCallback", arg0)
}

// SetIncomingMessageCallback indicates an expected call of SetIncomingMessageCallback
func (mr *MockEventedChatSystemMockRecorder) SetIncomingMessageCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIncomingMessageCallback", reflect.TypeOf((*MockEventedChatSystem)(nil).SetIncomingMessageCallback), arg0)
}

// UnmarshalMessageHandle mocks base method
func (m *MockEventedChatSystem) UnmarshalMessageHandle(arg0 string) (messages.MessageHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalMessageHandle", arg0)
	ret0, _ := ret[0].(messages.MessageHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalMessageHandle indicates an expected call of UnmarshalMessageHandle
func (mr *MockEventedChatSystemMockRecorder) UnmarshalMessageHandle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalMessageHandle", reflect.TypeOf((*MockEventedChatSystem)(nil).UnmarshalMessageHandle), arg0)
}
